# Generated by Django 5.0.4 on 2024-05-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_calcado_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcado',
            name='marca',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterModelTable(
            name='calcado',
            table='calcado',
        ),
    ]
