# Generated by Django 5.0.4 on 2024-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_calcado_marca_alter_calcado_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcado',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço'),
        ),
    ]
